# Generated by Django 5.0.3 on 2025-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
