# Generated by Django 5.0.3 on 2025-05-05 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_password_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_password_reset',
        ),
        migrations.AddField(
            model_name='user',
            name='password_update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
