# Generated by Django 5.0.3 on 2024-10-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0007_icons_remove_notebooks_notebooks_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooks',
            name='notebooksbrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notebooksbrand_id', to='Home_Page.notebooksbrand'),
            preserve_default=False,
        ),
    ]
