# Generated by Django 5.0.3 on 2024-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0009_icons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebooks',
            old_name='notebooksbrand_id',
            new_name='noteb_id',
        ),
    ]
