# Generated by Django 5.0.3 on 2024-11-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0010_icons_rename_notebooksbrand_id_notebooks_noteb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='notebooks_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_id', to='Home_Page.notebooks'),
        ),
    ]
