# Generated by Django 5.0.3 on 2024-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0014_icons_notebooks_processor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop_processors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100, verbose_name='Процесор')),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='processor_initial',
        ),
        migrations.RemoveField(
            model_name='notebooks',
            name='processor_id',
        ),
    ]
