# Generated by Django 5.0.3 on 2024-08-21 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('url_name', models.URLField()),
                ('images', models.ImageField(max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NotebooksBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url_name', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SmartHun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Чорновик'), (True, 'Опубліковано')], default=0)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('images_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_id', to='Home_Page.notebooks')),
            ],
        ),
        migrations.AddField(
            model_name='notebooks',
            name='Notebooks_brand',
            field=models.ManyToManyField(blank=True, to='Home_Page.notebooksbrand'),
        ),
    ]
