# Generated by Django 5.0.3 on 2024-10-05 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0003_icons_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФІО')),
                ('rating', models.TextField(blank=True, null=True, verbose_name='Оцінка')),
                ('reviews_users', models.CharField(verbose_name='Відгук користувача')),
                ('laptops_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_id', to='Home_Page.laptop')),
            ],
        ),
    ]
