# Generated by Django 5.0.3 on 2024-10-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0005_icons_laptop_notebooks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooksbrand',
            name='notebooks_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Home_Page.notebooks'),
        ),
    ]
