# Generated by Django 5.0.3 on 2024-10-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0008_icons_notebooks_notebooksbrand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebooks',
            old_name='notebooksbrand',
            new_name='notebooksbrand_id',
        ),
    ]
