# Generated by Django 5.0.3 on 2024-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0012_icons_laptop_processors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop_processors',
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_initial',
            field=models.CharField(default=1, verbose_name='Ініціали процесорів'),
            preserve_default=False,
        ),
    ]
